global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'octopus-hackathon'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'octopus-api'
    static_configs:
      - targets: ['octopus-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['minio:9000']
